### ISSUE TITLE
Support to covert back from IANA to windows

### ISSUE THREAD

**Issue by Tinadim** [rubenillodo/windows-iana#1]
I believe it would be nice to add support to add support to covert timezones the other way. I noticed some other libs that do it and if I'm not wrong one of them even forked from this repo. But I believe it would be nicer to keep it altogether in this lib. I already have the code for a pull request (with tests and lint passing), but wasn't able to send it to the repo. Let me know if you want me to send it!

**Comment by willyboy** [comment]
https://github.com/rubenillodo/windows-iana/pull/3
