### ISSUE TITLE
Misspelling

### ISSUE THREAD

**Issue by yakimko** [rubenillodo/windows-iana#12]
https://github.com/rubenillodo/windows-iana/blob/5b9151f70b85ef2f714d7c5fcb4deaf554794095/windowsZones.json#L93

Alaskan -> Alaska

**Comment by rubenillodo** [comment]
In the [source file](https://github.com/unicode-org/cldr/blob/master/common/supplemental/windowsZones.xml) we use to get all the Windows zones, it appears as `Alaskan`, sorry. 😞
