### ISSUE TITLE
Readme contains import of removed method

### ISSUE THREAD

**Issue by w01fgang** [rubenillodo/windows-iana#23]
`findOneIana` is removed in the latest release and wasn't updated in the example
![Screenshot from 2021-02-26 18-12-20](https://user-images.githubusercontent.com/8686751/109332383-4e3fe000-785e-11eb-8f18-0e97c87918bc.png)

**Comment by rubenillodo** [comment]
Oops, thanks for pointing this out!

Fixed with https://github.com/rubenillodo/windows-iana/commit/787be6a0231e2d0cca51c8e7bb4ecd3ff65b4d65.
